server:
  port: 5000
  servlet:
    context-path: /identity # This is the context path for the application use in load balancer

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true


jwt:
  signerKey: "iMfQAT1R9lSEHKQUOl0FBWnCEtjrdedSpX6S2fKQjQ1kJ4M+FbWkrf8sfFlNot9Y"